export class IntelligenceMods {
    static languages = {
        0: `Illiterate`,
        1: `Illiterate`,
        2: `Illiterate`,
        3: `Illiterate`,
        4: `Illiterate`,
        5: `Illiterate`,
        6: `Illiterate`,
        7:  unescape('%B1') + 0,
        8:  unescape('%B1') + 0,
        9:  unescape('%B1') + 0,
        10: unescape('%B1') + 0,
        11: unescape('%B1') + 0,
        12: unescape('%B1') + 0,
        13: +1,
        14: +1,
        15: +1,
        16: +1,
        17: +2,
        18: +3,
    };
    static bonusSpellsDay = {
        0: `N/A`,
        1: `N/A`,
        2: `N/A`,
        3: `N/A`,
        4: `N/A`,
        5: `N/A`,
        6: `N/A`,
        7: `N/A`,
        8: `N/A`,
        9:  `-`,
        10: `-`,
        11: `-`,
        12: `-`,
        13: `One Level 1`,
        14: `One Level 1`,
        15: `One Level 2`,
        16: `One Level 2`,
        17: `One Level 3`,
        18: `One Level 4`,
    };
    static learnNewSpell = {
        0: `N/A`,
        1: `N/A`,
        2: `N/A`,
        3: `N/A`,
        4: `N/A`,
        5: `N/A`,
        6: `N/A`,
        7: `N/A`,
        8: `N/A`,
        9:  `50%`,
        10: `50%`,
        11: `50%`,
        12: `50%`,
        13: `65%`,
        14: `65%`,
        15: `75%`,
        16: `75%`,
        17: `85%`,
        18: `95%`,
    };
};